devil:            "The dead grandmother is killing everyone."
the-crucible:     "It's not really about the Salem Witch Trial."
the-others:       "Nicole Kidman is the one who's actually dead. The 'ghosts' are live people in our world."
the-godfather-2:  "Fredo sold Michael out. He broke his heart."
the-crying-game:  "Dil - The beautiful woman is actually a man and it complicates Stephen Rea's character's feelings."